name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/tests.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/tests.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Run unit tests
        run: pnpm test:ci
